CREATE DATABASE lv_safety_verification;
use lv_safety_verification;


-----------> LPS <----------

			CREATE TABLE BASIC_LPS_TABLE(
						BASIC_LPS_ID INT AUTO_INCREMENT,
						CLIENT_NAME VARCHAR(225),
						PROJECT_NAME VARCHAR(225),
						PMC_NAME VARCHAR(225),
						CONSULTANT_NAME VARCHAR(225),
						CONTRACTOR_NAME VARCHAR(225),
						DEALER_CONTRACTOR VARCHAR(225),
						ADDRESS VARCHAR(225),
						LOCATION VARCHAR(225),
						INSTALLATION_CONTRACTOR VARCHAR(225),
						INDUSTRY_TYPE VARCHAR(225),
						SOIL_RESISTIVITY VARCHAR(225),
						USER_NAME VARCHAR(225),
						ALL_STEPS_COMPLETED VARCHAR(10),
						CREATED_BY VARCHAR(255),
					    CREATED_DATE datetime,
					    UPDATED_BY VARCHAR(255),
			            UPDATED_DATE datetime,
						CONSTRAINT PK_BASIC_LPS_ID PRIMARY KEY(BASIC_LPS_ID)
			);
			
			
	-----------> LPS AIR-TERMINALS <----------	
		  CREATE TABLE AIR_TERMINATION_DETAILS_TABLE(
		  		  AIR_TERMINATION_DETAILS_ID INT AUTO_INCREMENT,
		  		  USER_NAME VARCHAR(225),
                  BASIC_LPS_ID INT,               
                  CREATED_BY VARCHAR(255),
			      CREATED_DATE datetime,
				  UPDATED_BY VARCHAR(255),
			      UPDATED_DATE datetime,
                  CONSTRAINT PK_AIR_TERMINATION_DETAILS_ID PRIMARY KEY(AIR_TERMINATION_DETAILS_ID)
		  		 	              
		  );
		  
			
          CREATE TABLE LPSAIRDESCRIPTION_TABLE(
                  LPSAIRDESCRIPTION_ID INT AUTO_INCREMENT,
                  AIR_TERMINATION_DETAILS_ID INT,
                  BUILDING_NUMBER INT,
	              BUILDING_NAME VARCHAR(255),
	              BUILDING_COUNT INT NOT NULL,		
	              BUILDING_TYPE VARCHAR(255),
	              BUILDING_LENGTH INT,
	              BUILDING_WIDTH INT,
	              BUILDING_HEIGHT INT,
	              PROTECTION_LEVEL VARCHAR(255),
	              FLAG VARCHAR(20),
                  CONSTRAINT PK_LPSAIRDESCRIPTION_ID PRIMARY KEY(LPSAIRDESCRIPTION_ID),
                  CONSTRAINT FK_LPSAIRDESCRIPTION_AIR_TERMINATION_DETAILS_ID FOREIGN KEY(AIR_TERMINATION_DETAILS_ID) REFERENCES AIR_TERMINATION_DETAILS_TABLE(AIR_TERMINATION_DETAILS_ID) ON DELETE CASCADE
                  
);

		  

		  CREATE TABLE AIR_BASIC_DESCRIPTION_TABLE(
					AIR_BASIC_DESCRIPTION_ID INT AUTO_INCREMENT,
					LPSAIRDESCRIPTION_ID INT,
					APPROVED_COPYOF_DRAWING_OBSERVATION VARCHAR(225),
					APPROVED_COPYOF_DRAWING_REMARKS VARCHAR(225),
					ARCHITECT_NAMEINOBSERVATION VARCHAR(225),
					ARCHITECT_NAMEINREMARKS VARCHAR(225),
					DATE_OF_DESIGN_OBSERVATION VARCHAR(225),
					DATE_OF_DESIGN_REMARKS VARCHAR(225),
				    OBSERVATION_APPROVED_BY VARCHAR(225),
					REMARKS_APPROVED_BY VARCHAR(225),
					DATEOF_APPROVAL_OB VARCHAR(225),
					DATEOF_APPROVAL_REM VARCHAR(225),
					OBSERVATION_DRAWING_NUMBER VARCHAR(225),
					REMARKS_DRAWING_NUMBER VARCHAR(225),
					OBSERVATION_REVISION_NUMBER VARCHAR(225),
					REMARKS_REVISION_NUMBER VARCHAR(225),
					OBSERVATION_DEVIATION_CHECKING VARCHAR(225),
					REMARKS_DEVIATION_CHECKING VARCHAR(225),
					OBSERVATION_QUALITY_OF_INSTALLATION VARCHAR(225),
					REMARKS_QUALITY_OF_INSTALLATION VARCHAR(225),
					CONNECTION_MADE_BRAZINGOBSERVATION VARCHAR(225),
	                CONNECTION_MADE_BRAZINGREMARKS VARCHAR(225),
	                ELECTRICAL_EQUIPMENT_PLACEDOBSERVATION VARCHAR(225),
	                ELECTRICAL_EQUIPMENT_PLACEDREMARKS VARCHAR(225),
	                COMBUSTABLE_PARTOBSERVATION VARCHAR(225),
	                COMBUSTABLE_PARTREMARKS VARCHAR(225),
	                TERMINATION_MESH_CONDUCTOROBSERVATION VARCHAR(225),
	                TERMINATION_MESH_CONDUCTORREMARKS VARCHAR(225),
	                BONDING_EQUIPOTENTIALOBSERVATION VARCHAR(225),
	                BONDING_EQUIPOTENTIALREMARKS VARCHAR(225),
					CONSTRAINT PK_AIR_BASIC_DESCRIPTION_ID PRIMARY KEY(AIR_BASIC_DESCRIPTION_ID),
	                CONSTRAINT FK_BASICDESCRIPTION_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES LPSAIRDESCRIPTION_TABLE(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
			);
		

          CREATE TABLE LPSVERTICALAIRTERMINAL_TABLE(
                  LPSVERTICALAIRTERMINAL_ID INT AUTO_INCREMENT,
                  LPSAIRDESCRIPTION_ID INT,
                  FLAG BOOLEAN,
                  INSTALLATION_TERMINATIONSYSTEM_OB VARCHAR(225),
                  INSTALLATION_TERMINATIONSYSTEM_REM VARCHAR(225),
                  PHYSICAL_INSPECTIONOBSERVATION VARCHAR(225),
                  PHYSICAL_INSPECTIONREMARKS VARCHAR(225),
                  MATERIAL_OF_TERMINALOBSERVATION  VARCHAR(225),
                  MATERIAL_OF_TERMINALREMARKS  VARCHAR(225),
                  SIZE_OF_TERMINALOBSERVATION   VARCHAR(225),
                  SIZE_OF_TERMINALREMARKS   VARCHAR(225),
                  HEIGHT_OF_TERMINALOBSERVATION  VARCHAR(225),
                  HEIGHT_OF_TERMINALREMARKS   VARCHAR(225),
                  ANGLEPROTECTION_HEIGHTOBSERVATION VARCHAR(225),
                  ANGLEPROTECTION_HEIGHTREMARKS   VARCHAR(225),
                  INSTALLATION_PROTRUDESOBSERVATION  VARCHAR(225),
                  INSTALLATION_PROTRUDESREMARKS  VARCHAR(225),
                  SUPPORT_FLATSURFACEOBSERVATION  VARCHAR(225),
                  SUPPORT_FLATSURFACEREMARKS  VARCHAR(225),
                  HEIGHT_FLATSURAFACEOBSERVATION  VARCHAR(225),
                  HEIGHT_FLATSURAFACEREMARKS  VARCHAR(225),
                  VAT_TO_ROOFCONDUCTOROBSERVATION   VARCHAR(225),
                  VAT_TO_ROOFCONDUCTORREMARKS  VARCHAR(225),
                  TOTAL_NUMBEROBSERVATION  VARCHAR(225),
                  TOTAL_NUMBERREMARKS  VARCHAR(225),
                  INSP_NO_OBS VARCHAR(225),
                  INSP_NO_REM VARCHAR(225),
                  INSP_PASSED_NO_OBS VARCHAR(225),
                  INSP_PASSED_NO_REM VARCHAR(225),
                  INSP_FAILED_NO_OBS VARCHAR(225),
                  INSP_FAILED_NO_REM VARCHAR(225),
                  CONSTRAINT PK_LPSVERTICALAIRTERMINAL_ID  PRIMARY KEY(LPSVERTICALAIRTERMINAL_ID),
                  CONSTRAINT FK_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES LPSAIRDESCRIPTION_TABLE(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);

          CREATE TABLE AIR_MESHDESCRIPTION_TABLE(
                  MESHDESCRIPTION_ID INT AUTO_INCREMENT,
                  LPSAIRDESCRIPTION_ID INT,
                  FLAG BOOLEAN,
                  PHYSICAL_INSPECTION_OB VARCHAR(225),
                  PHYSICAL_INSPECTION_REM VARCHAR(225),
                  MATERIAL_OFCONDUCTOR_OB VARCHAR(225),
                  MATERIAL_OFCONDUCTOR_REM VARCHAR(225),
                  SIZE_OF_CONDUCTOROBSERVATION VARCHAR(225),
                  SIZE_OF_CONDUCTORREMARKS VARCHAR(225),
                  MESH_SIGEOBSERVATION VARCHAR(225),
                  MESH_SIGEREMARKS VARCHAR(225),
                  MAXIMUM_DISTANCEOBSERVATION VARCHAR(225),
                  MAXIMUM_DISTANCEREMARKS VARCHAR(225),
                  MINIMUM_DISTANCEOBSERVATION VARCHAR(225),
                  MINIMUM_DISTANCEREMARKS VARCHAR(225),
                  HEIGHT_OFCONDUCTOR_FLATSURAFACEOBSERVATION  VARCHAR(225),
                  HEIGHT_OFCONDUCTOR_FLATSURAFACEREMARKS VARCHAR(225),
                  CONSTRAINT PK_MESHDESCRIPTION_ID   PRIMARY KEY(MESHDESCRIPTION_ID),
                  CONSTRAINT FK_MESHDESCRIPTION_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES LPSAIRDESCRIPTION_TABLE(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);


          CREATE TABLE AIR_HOLDERS_DESCRIPTION_TABLE(
                  HOLDERS_DESCRIPTION_ID INT AUTO_INCREMENT,
                  LPSAIRDESCRIPTION_ID INT,                  
                  FLAG BOOLEAN,
                  PHYSICAL_INSPECTION_OBSERVATION VARCHAR(225),
                  PHYSICAL_INSPECTION_REMARKS VARCHAR(225),
                  CONDUCTORHOLDER_FLATSURAFACE_OBSERVATION  VARCHAR(225),
                  CONDUCTORHOLDER_FLATSURAFACE_REMARKS VARCHAR(225),
                  CODUCTOR_HOLDER_OBSERVATION VARCHAR(225),
                  CODUCTOR_HOLDER_REMARKS VARCHAR(225),
                  HOLDER_TYPE_OBSERVATION VARCHAR(225),
                  HOLDER_TYPE_REMARKS VARCHAR(225),
                  MATERIAL_HOLDER_OBSERVATION VARCHAR(225),
                  MATERIAL_HOLDER_REMARKS VARCHAR(225),
                  TOTAL_HOLDERSNO_OBSERVATION VARCHAR(225),
                  TOTAL_HOLDERSNO_REMARKS VARCHAR(225),
                  TOTALPARPET_HOLDER_OBSERVATION VARCHAR(225),
                  TOTALPARPET_HOLDER_REMARKS VARCHAR(225),
                  HO_INSP_NO_OBS VARCHAR(225),
                  HO_INSP_NO_REM VARCHAR(225),
                  HO_INSP_PASSED_NO_OBS VARCHAR(225),
                  HO_INSP_PASSED_NO_REM VARCHAR(225),
                  HO_INSP_FAILED_NO_OBS VARCHAR(225),
                  HO_INSP_FAILED_NO_REM VARCHAR(225),
                  PH_INSP_NO_OBS VARCHAR(225),
                  PH_INSP_NO_REM VARCHAR(225),
                  PH_INSP_PASSED_NO_OBS VARCHAR(225),
                  PH_INSP_PASSED_NO_REM VARCHAR(225),
                  PH_INSP_FAILED_NO_OBS VARCHAR(225),
                  PH_INSP_FAILED_NO_REM VARCHAR(225),
                  CONSTRAINT PK_HOLDERS_DESCRIPTION_ID   PRIMARY KEY(HOLDERS_DESCRIPTION_ID ),
                 CONSTRAINT FK_HOLDERS_DESCRIPTION_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES LPSAIRDESCRIPTION_TABLE(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);


          CREATE TABLE AIR_CLAMPS_TABLE(
                  CLAMPS_ID INT AUTO_INCREMENT,
                  LPSAIRDESCRIPTION_ID INT,
                  FLAG BOOLEAN,
                  PHYSICAL_INSPECTION_OBSERVATION VARCHAR(225),
                  PHYSICAL_INSPECTION_REMARKS VARCHAR(225),
                  CONDUCTORCLAMPS_FLATSURAFACE_OBSERVATION VARCHAR(225),
                  CONDUCTORCLAMPS_FLATSURAFACE_REMARKS VARCHAR(225),
                  INTERCONNECTION_OF_CLAMPS_OBSERVATION VARCHAR(225),
                  INTERCONNECTION_OF_CLAMPS_REMARKS VARCHAR(225),
                  CLAMP_TYPE_OBSERVATION VARCHAR(225),
                  CLAMP_TYPE__REMARKS VARCHAR(225),
                  MATERIAL_OF_CLAMPS_OBSERVATION VARCHAR(225),
                  MATERIAL_OF_CLAMPS_REMARKS VARCHAR(225),
                  TOTAL_CLAMPSNO_OBSERVATION VARCHAR(225),
                  TOTAL_CLAMPSNO_REMARKS VARCHAR(225),
                  INSP_NO_OBS VARCHAR(225),
                  INSP_NO_REM VARCHAR(225),
                  INSP_PASSED_NO_OBS VARCHAR(225),
                  INSP_PASSED_NO_REM VARCHAR(225),
                  INSP_FAILED_NO_OBS VARCHAR(225),
                  INSP_FAILED_NO_REM VARCHAR(225),
                  CONSTRAINT PK_CLAMPS_ID PRIMARY KEY(CLAMPS_ID),
                  CONSTRAINT FK_CLAMPS_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES LPSAIRDESCRIPTION_TABLE(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);


         CREATE TABLE AIR_EXPANSION_TABLE(
                  EXPANSION_ID INT AUTO_INCREMENT,
                  LPSAIRDESCRIPTION_ID INT,
                  FLAG BOOLEAN,
                  PHYSICAL_INSPECTION_OBSERVATION VARCHAR(225),
                  PHYSICAL_INSPECTION_REMARKS VARCHAR(225),
                  STRIGHTCONNECTOR_PIECS_OBSERVATION  VARCHAR(225),
                  STRIGHTCONNECTOR_PIECS_REMARKS  VARCHAR(225),
                  MATERIAL_OF_EXPANSIONPIECE_OBSERVATION  VARCHAR(225),
                  MATERIAL_OF_EXPANSIONPIECE_REMARKS VARCHAR(225),
                  TOTALNO_EXPANSIONPIECE_OBSERVATION VARCHAR(225),
                  TOTALNO_EXPANSIONPIECE_REMARKS VARCHAR(225),
                  INSP_NO_OBS VARCHAR(225),
                  INSP_NO_REM VARCHAR(225),
                  INSP_PASSED_NO_OBS VARCHAR(225),
                  INSP_PASSED_NO_REM VARCHAR(225),
                  INSP_FAILED_NO_OBS VARCHAR(225),
                  INSP_FAILED_NO_REM VARCHAR(225),
                  CONSTRAINT PK_EXPANSION_ID PRIMARY KEY(EXPANSION_ID),
                  CONSTRAINT FK_EXPANSION_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES LPSAIRDESCRIPTION_TABLE(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);



           CREATE TABLE AIR_CONNECTORS_TABLE(
                   CONNECTORS_ID INT AUTO_INCREMENT,
                   LPSAIRDESCRIPTION_ID INT,
                   FLAG BOOLEAN,
                   PHYSICAL_INSPECTION_OBSERVATION VARCHAR(225),
                   PHYSICAL_INSPECTION_REMARKS VARCHAR(225),
                   CHECKCONNECTION_CONNECTORS_OBSERVATION VARCHAR(225),
                   CHECKCONNECTION_CONNECTORS_REMARKS VARCHAR(225),
                   MATERIAL_OF_CONNECTORS_OBSERVATION VARCHAR(225),
                   MATERIAL_OF_CONNECTORS_REMARKS VARCHAR(225),
                   STRIGHT_CONNECTORS_OBSERVATION VARCHAR(225),
                   STRIGHT_CONNECTORS_REMARKS VARCHAR(225),
                   T_CONNECTORS_OBSERVATION VARCHAR(225),
                   T_CONNECTORS_REMARKS VARCHAR(225),
                   L_CONNECTORS_OBSERVATION VARCHAR(225),
                   L_CONNECTORS_REMARKS VARCHAR(225),
                   TOTALNO_CONNECTORS_OBSERVATION VARCHAR(225),
                   TOTALNO_CONNECTORS_REMARKS VARCHAR(225),
                   INSP_NO_OBS VARCHAR(225),
                   INSP_NO_REM VARCHAR(225),
                   INSP_PASSED_NO_OBS VARCHAR(225),
                   INSP_PASSED_NO_REM VARCHAR(225),
                   INSP_FAILED_NO_OBS VARCHAR(225),
                   INSP_FAILED_NO_REM VARCHAR(225),
                   CONSTRAINT PK_CONNECTORS_ID PRIMARY KEY(CONNECTORS_ID),
                   CONSTRAINT FK_CONNECTORS_LPSAIRDESCRIPTION_ID FOREIGN KEY(LPSAIRDESCRIPTION_ID) REFERENCES LPSAIRDESCRIPTION_TABLE(LPSAIRDESCRIPTION_ID) ON DELETE CASCADE
);

			
                 
                 
        -----------> LPS DOWN-CONDUCTOR <----------	         
                 
                 
             CREATE TABLE DOWNCONDUCTORDESCRIPTION_TABLE(
                          DOWNCONDUCTORDESCRIPTION_ID INT AUTO_INCREMENT,
                          BASIC_LPS_ID INT,
                          USER_NAME VARCHAR(225),
                          FLAG BOOLEAN,
                          BI_METALLICISSUE_OB VARCHAR(225),
                          BI_METALLICISSUE_REM VARCHAR(225),
                          WARNINGNOTICE_GROUNDLEVEL_OB VARCHAR(225),
                          WARNINGNOTICE_GROUNDLEVEL_REM VARCHAR(225),
                          NOPOWER_DOWNCONDUCTOR_OB VARCHAR(225),
                          NOPOWER_DOWNCONDUCTOR_REM VARCHAR(225),
                          CONNECTIONSMADE_BY_BRAZING_OB VARCHAR(225),
                          CONNECTIONSMADE_BY_BRAZING_REM VARCHAR(225),
                          CHEMICAL_SPRINKLER_OB VARCHAR(225),
                          CHEMICAL_SPRINKLER_REM VARCHAR(225),
                          COMBUSTIBLEMATERIAL_WALL_OB VARCHAR(225),
                          COMBUSTIBLEMATERIAL_WALL_REM VARCHAR(225),
                          CREATED_BY VARCHAR(255),
                          CREATED_DATE datetime,
                          UPDATED_BY VARCHAR(255),
                          UPDATED_DATE datetime,
                          
                          CONSTRAINT PK_DOWNCONDUCTORDESCRIPTION_ID PRIMARY KEY(DOWNCONDUCTORDESCRIPTION_ID)
);


		   CREATE TABLE DOWNCONDUCTOR_TABLE(
						DOWNCONDUCTOR_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
					    LOCATION_NUMBER INT,
                        LOCATION_NAME VARCHAR(225),
                        FLAG BOOLEAN,
						PHYSICAL_INSPECTION_OB VARCHAR(225),
						PHYSICAL_INSPECTION_REM VARCHAR(225),
						CONDUCTOR_MATERIAL_OB VARCHAR(225),
						CONDUCTOR_MATERIAL_REM VARCHAR(225),
						CONDUCTOR_SIZE_OB VARCHAR(225),
						CONDUCTOR_SIZE_REM VARCHAR(225),
						DOWNCONDUCTOR_EXPOSED_OB VARCHAR(225),
						DOWNCONDUCTOR_EXPOSED_RE VARCHAR(225),
						DOWNCONDUCTOR_LOCATION_OB VARCHAR(225),
						DOWNCONDUCTOR_LOCATION_REM VARCHAR(225),
						DOWNCONDUCTOR_GUTTERS_OB VARCHAR(225),
						DOWNCONDUCTOR_GUTTERS_REM VARCHAR(225),
						ENSURE_DOWNCONDUCTOR_OB VARCHAR(225),
						ENSURE_DOWNCONDUCTOR_REM VARCHAR(225),
						INSTALLATION_DOWNCONDUCTOR_OB VARCHAR(225),
						INSTALLATION_DOWNCONDUCTOR_REM VARCHAR(225),
						MAXIMUM_DOWNCONDUCTOR_OB VARCHAR(225),
						MAXIMUM_DOWNCONDUCTOR_REM VARCHAR(225),
						MINIMUM_DOWNCONDUCTOR_OB VARCHAR(225),
						MINIMUM_DOWNCONDUCTOR_REM VARCHAR(225),
						TOTALNO_DOWNCONDUCTOR_OB VARCHAR(225),
						TOTALNO_DOWNCONDUCTOR_REM VARCHAR(225),
						INSPECTED_NO_OB VARCHAR(225),
						INSPECTED_NO_REM VARCHAR(225),
						INSPECTIONSPASSED_NO_OB VARCHAR(225),
						INSPECTIONSPASSED_NO_REM VARCHAR(225),
						INSPECTIONFAILED_NO_OB VARCHAR(225),
						INSPECTIONFAILED_NO_REM VARCHAR(225),
						
						CONSTRAINT PK_DOWNCONDUCTOR_ID PRIMARY KEY(DOWNCONDUCTOR_ID),
						CONSTRAINT FK_DOWNCONDUCTOR_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES DOWNCONDUCTORDESCRIPTION_TABLE(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);


           CREATE TABLE BRIDGINGDESCRIPTION_TABLE(
						BRIDGINGDESCRIPTION_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
						LOCATION_NUMBER INT,
						LOCATION_NAME VARCHAR(225),
						FLAG BOOLEAN,
						ENSURE_BRIDGINGCABLE_OB VARCHAR(225),
						ENSURE_BRIDGINGCABLE_REM VARCHAR(225),
						ALUMINIUMCONDUCTOR_SIDEWALL_OB VARCHAR(225),
						ALUMINIUMCONDUCTOR_SIDEWALL_REM VARCHAR(225),
						BRIDGINGCABLE_CONNECTION_OB VARCHAR(225),
						BRIDGINGCABLE_CONNECTION_REM VARCHAR(225),
						TOTALNO_BRIDGINGCABLE_OB VARCHAR(225),
						TOTALNO_BRIDGINGCABLE_REM VARCHAR(225),
						INSPECTED_NO_OB VARCHAR(225),
						INSPECTED_NO_REM VARCHAR(225),
						INSPECTIONSPASSED_NO_OB VARCHAR(225),
						INSPECTIONSPASSED_NO_REM VARCHAR(225),
						INSPECTIONFAILED_NO_OB VARCHAR(225),
						INSPECTIONFAILED_NO_REM VARCHAR(225),
						
						CONSTRAINT PK_BRIDGINGDESCRIPTION_ID PRIMARY KEY(BRIDGINGDESCRIPTION_ID ),
						CONSTRAINT FK_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES DOWNCONDUCTORDESCRIPTION_TABLE(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);


           CREATE TABLE HOLDERS_TABLE(
						HOLDERS_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
						LOCATION_NUMBER INT,
                        LOCATION_NAME VARCHAR(225),
                        FLAG BOOLEAN,
						PHYSICAL_INSPECTION_OB VARCHAR(225),
						PHYSICAL_INSPECTION_REM VARCHAR(225),
						CONDUCTORHOLDER_FLATSURFACE_OB VARCHAR(225),
						CONDUCTORHOLDER_FLATSURFACE_REM VARCHAR(225),
						CONDUCTOR_HOLDED_OB VARCHAR(225),
						CONDUCTOR_HOLDED_REM VARCHAR(225),
						MATERIAL_HOLDER_OB VARCHAR(225),
						MATERIAL_HOLDER_REM VARCHAR(225),
						TOTALNO_HOLDERS_OB VARCHAR(225),
						TOTALNO_HOLDERS_REM VARCHAR(225),
						INSPECTED_NO_OB VARCHAR(225),
						INSPECTED_NO_REM VARCHAR(225),
						INSPECTIONSPASSED_NO_OB VARCHAR(225),
						INSPECTIONSPASSED_NO_REM VARCHAR(225),
						INSPECTIONFAILED_NO_OB VARCHAR(225),
						INSPECTIONFAILED_NO_REM VARCHAR(225),
						
						CONSTRAINT PK_HOLDERS_ID PRIMARY KEY(HOLDERS_ID),
						CONSTRAINT FK_HOLDERS_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES DOWNCONDUCTORDESCRIPTION_TABLE(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE		
);


           CREATE TABLE CONNECTORS_TABLE(
						CONNECTORS_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
					    LOCATION_NUMBER INT,
                        LOCATION_NAME VARCHAR(225),
                        FLAG BOOLEAN,
						PHYSICAL_INSPECTION_OB VARCHAR(225),
						PHYSICAL_INSPECTION_REM VARCHAR(225),
						STRAIGHT_CONNECTORCHACK_OB VARCHAR(225),
						STRAIGHT_CONNECTORCHACK_REM VARCHAR(225),
						MATERIAL_CONNECTOR_OB VARCHAR(225),
						MATERIAL_CONNECTOR_REM VARCHAR(225),
						MAXCONNECTORS_DOWNCONDUCTORS_OB VARCHAR(225),
						MAXCONNECTORS_DOWNCONDUCTORS_REM VARCHAR(225),
						TOTALNO_CONNECTORS_OB VARCHAR(225),
						TOTALNO_CONNECTORS_REM VARCHAR(225),
						INSPECTED_NO_OB VARCHAR(225),
						INSPECTED_NO_REM VARCHAR(225),
						INSPECTIONSPASSED_NO_OB VARCHAR(225),
						INSPECTIONSPASSED_NO_REM VARCHAR(225),
						INSPECTIONFAILED_NO_OB VARCHAR(225),
						INSPECTIONFAILED_NO_REM VARCHAR(225),
						
						CONSTRAINT PK_CONNECTORS_ID PRIMARY KEY(CONNECTORS_ID),
						CONSTRAINT FK_CONNECTORS_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES DOWNCONDUCTORDESCRIPTION_TABLE(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);

           CREATE TABLE LIGHTNINGCOUNTERS_TABLE(
						LIGHTNINGCOUNTERS_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
						LOCATION_NUMBER INT,
                        LOCATION_NAME VARCHAR(225),
                        FLAG BOOLEAN,
						THREADHOLD_CURRENT_OB VARCHAR(225),
						THREADHOLD_CURRENT_REM VARCHAR(225),
						MAXIMUMWITHSTAND_CURRENT_OB VARCHAR(225),
						MAXIMUMWITHSTAND_CURRENT_REM VARCHAR(225),
						COUNTS_OB VARCHAR(225),
						COUNTS_REM VARCHAR(225),
						BATTERY_LIFETIME_OB VARCHAR(225),
						BATTERY_LIFETIME_REM VARCHAR(225),
						PROPERCONNECTION_LIGHTINGCOUNTER_OB VARCHAR(225),
						PROPERCONNECTION_LIGHTINGCOUNTER_REM VARCHAR(225),
						LIGHTINGCOUNTER_PLACED_OB VARCHAR(225),
						LIGHTINGCOUNTER_PLACED_REM VARCHAR(225),
						CONDITION_OF_LIGHTINGCOUNTER_OB VARCHAR(225),
						CONDITION_OF_LIGHTINGCOUNTER_REM VARCHAR(225),
						TOTALNO_LIGHTNINGCOUNTER_OB VARCHAR(225),
						TOTALNO_LIGHTNINGCOUNTER_REM VARCHAR(225),
						INSPECTED_NO_OB VARCHAR(225),
						INSPECTED_NO_REM VARCHAR(225),
						INSPECTIONSPASSED_NO_OB VARCHAR(225),
						INSPECTIONSPASSED_NO_REM VARCHAR(225),
						INSPECTIONFAILED_NO_OB VARCHAR(225),
						INSPECTIONFAILED_NO_REM VARCHAR(225),
						
						CONSTRAINT PK_LIGHTNINGCOUNTERS_ID PRIMARY KEY(LIGHTNINGCOUNTERS_ID ),
						CONSTRAINT FK_LIGHTNINGCOUNTERS_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES DOWNCONDUCTORDESCRIPTION_TABLE(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);


		   CREATE TABLE TESTJOINTS_TABLE(
						TESTJOINT_ID INT AUTO_INCREMENT,
						DOWNCONDUCTORDESCRIPTION_ID INT,
						LOCATION_NUMBER INT,
                        LOCATION_NAME VARCHAR(225),
						FLAG BOOLEAN,
						TESTJOINT_TYPE_OB VARCHAR(225),
						TESTJOINT_TYPE_REM VARCHAR(225),
						MATERIAL_TESTJOINT_OB VARCHAR(225),
						MATERIAL_TESTJOINT_REM VARCHAR(225),
						ACCESSIBILITY_OF_TESTJOINT_OB VARCHAR(225),
						ACCESSIBILITY_OF_TESTJOINT_REM VARCHAR(225),
						NONMETALICCASING_PROTECTION_OB VARCHAR(225),
						NONMETALICCASING_PROTECTION_REM VARCHAR(225),
						TESTJOINTPLACED_GROUNTLEVEL_OB VARCHAR(225),
						TESTJOINTPLACED_GROUNTLEVEL_REM VARCHAR(225),
						BIMETALLICISSUE_CHECK_OB VARCHAR(225),
						BIMETALLICISSUE_CHECK_REM VARCHAR(225),
						TOTALNO_OF_TESTJOINT_OB VARCHAR(225),
						TOTALNO_OF_TESTJOINT_REM VARCHAR(225),
						INSPECTED_NO_OB VARCHAR(225),
						INSPECTED_NO_REM VARCHAR(225),
						INSPECTIONSPASSED_NO_OB VARCHAR(225),
						INSPECTIONSPASSED_NO_REM VARCHAR(225),
						INSPECTIONFAILED_NO_OB VARCHAR(225),
						INSPECTIONFAILED_NO_REM VARCHAR(225),
						
						CONSTRAINT PK_TESTJOINT_ID PRIMARY KEY(TESTJOINT_ID),
						CONSTRAINT FK_TESTJOINTS_DOWNCONDUCTORDESCRIPTION_ID FOREIGN KEY(DOWNCONDUCTORDESCRIPTION_ID) REFERENCES DOWNCONDUCTORDESCRIPTION_TABLE(DOWNCONDUCTORDESCRIPTION_ID) ON DELETE CASCADE
);







        -----------> LPS EARTHING-TABLE <----------	  

           	CREATE TABLE EARTHING_LPS_DESCRIPTION(
							EARTHING_ID INT AUTO_INCREMENT,
							EARTHING_TYPEINOB VARCHAR(225),
							EARTHING_TYPEINREM VARCHAR(225),
							BASIC_LPS_ID INT,
							USER_NAME VARCHAR(225),
							BIMETALLIC_ISSUEINOB VARCHAR(225),
							BIMETALLIC_ISSUEINREM VARCHAR(225),
							BRAZING_CONNECTIONSINOB VARCHAR(225),
							BRAZING_CONNECTIONSINREM VARCHAR(225),
							LOCATION_NUMBER VARCHAR(225),
							LOCATION_NAME VARCHAR(225),
							CREATED_BY VARCHAR(255),
							CREATED_DATE datetime,
							UPDATED_BY VARCHAR(255),
							UPDATED_DATE datetime,
							CONSTRAINT PK_EARTHING_ID PRIMARY KEY(EARTHING_ID)
							);



				CREATE TABLE EARTHDESCRIPTION_TABLE(
							EARTHDESCRIPTION_ID INT AUTO_INCREMENT,
							EARTHING_ID INT,
						    LOCATION_NUMBER INT,
                            LOCATION_NAME VARCHAR(225),
                            FLAG BOOLEAN,
							SOIL_RESISTIVITYINOB VARCHAR(225),
							SOIL_RESISTIVITYINREM VARCHAR(225),
							EARTHPIT_DIGGINGINOB VARCHAR(225),
							EARTHPIT_DIGGINGINREM VARCHAR(225),
							EARTHELECTRODE_LESSTHAN_DOWNCONDUCTORSINOB VARCHAR(225),
							EARTHELECTRODE_LESSTHAN_DOWNCONDUCTORSINREM VARCHAR(225),
							CONNECTED_EARTHTERMINATIONINOB VARCHAR(225),
							CONNECTED_EARTHTERMINATIONINREM VARCHAR(225),
							TESTJOINT_EARTHELECTRODEINOB VARCHAR(225),
							TESTJOINT_EARTHELECTRODEINREM VARCHAR(225),
							GROUNTLEVEL_COMPOUNTFILLEDINOB VARCHAR(225),
							GROUNTLEVEL_COMPOUNTFILLEDINREM VARCHAR(225),
							EARTHELCTRODE_LOCATIONINOB VARCHAR(225),
							EARTHELCTRODE_LOCATIONINREM VARCHAR(225),
							EARTHELECTRODE_MATERIALINOB VARCHAR(225),
							EARTHELECTRODE_MATERIALINREM VARCHAR(225),
							EARTHELECTRODE_SIZEINOB VARCHAR(225),
							EARTHELECTRODE_SIZEINREM VARCHAR(225),
							EARTHELECTRODE_LENGTHINOB VARCHAR(225),
							EARTHELECTRODE_LENGTHINREM VARCHAR(225),
							EARTHELECT_MAXIMUMDISTANCEWALLINOB VARCHAR(225),
							EARTHELECT_MAXIMUMDISTANCEWALLINREM VARCHAR(225),
							EARTHELECT_MINIMUMDISTANCEWALLINOB VARCHAR(225),
							EARTHELECT_MINIMUMDISTANCEWALLINREM VARCHAR(225),
							EARTHELECT_MAXIMUMDISTANCEINOB VARCHAR(225),
							EARTHELECT_MAXIMUMDISTANCEINREM VARCHAR(225),
							EARTHELECT_MINIMUMDISTANCEINOB VARCHAR(225),
							EARTHELECT_MINIMUMDISTANCEINREM VARCHAR(225),
							TOTALNUMBER_OF_ELECTRODEINOB VARCHAR(225),
							TOTALNUMBER_OF_ELECTRODEINREM VARCHAR(225),
							INSPECTED_NO_OB VARCHAR(225),
							INSPECTED_NO_REM VARCHAR(225),
							INSPECTIONSPASSED_NO_OB VARCHAR(225),
							INSPECTIONSPASSED_NO_REM VARCHAR(225),
							INSPECTIONFAILED_NO_OB VARCHAR(225),
							INSPECTIONFAILED_NO_REM VARCHAR(225),
							CONSTRAINT PK_EARTHDESCRIPTION_ID PRIMARY KEY(EARTHDESCRIPTION_ID),
							CONSTRAINT FK_EARTHING_ID FOREIGN KEY(EARTHING_ID) REFERENCES EARTHING_LPS_DESCRIPTION(EARTHING_ID) ON DELETE CASCADE
							);






				CREATE TABLE EARTHINGCLAMPS_TABLE(
							EARTHCLAMPS_ID INT AUTO_INCREMENT,
							EARTHING_ID INT,
							LOCATION_NUMBER INT,
                            LOCATION_NAME VARCHAR(225),
                            FLAG BOOLEAN,
							PHYSICAL_INSPECTIONINOB VARCHAR(225),
							PSYSICAL_INSPECTIONINREM VARCHAR(225),
							CLAMPS_FIRMLYOB VARCHAR(225),
							CLAMPS_FIRMLYINREM VARCHAR(225),
							INTERCONNECTION_OF_EARTHCLAMPSINOB VARCHAR(225),
							INTERCONNECTION_OF_EARTHCLAMPSINREM VARCHAR(225),
							TYPE_OF_CLAMPSINOB VARCHAR(225),
							TYPE_OF_CLAMPSINREM VARCHAR(225),
							MATERIAL_OF_CLAMPSINOB VARCHAR(225),
							MATERIAL_OF_CLAMPSINREM VARCHAR(225),
							TOTALNO_CLAMPSINOB VARCHAR(225),
							TOTALNO_CLAMPSINREM VARCHAR(225),
							INSPECTED_CLAMPSINOB VARCHAR(225),
							INSPECTED_CLAMPSINREM VARCHAR(225),
							INSPECTED_PASSEDINOB VARCHAR(225),
							INSPECTED_PASSEDINREM VARCHAR(225),
							INSPECTED_FAILEDINOB VARCHAR(225),
							INSPECTED_FAILEDINREM VARCHAR(225),
		
							CONSTRAINT PK_EARTHCLAMPS_ID PRIMARY KEY(EARTHCLAMPS_ID),
							CONSTRAINT FK_EARTHCLAMPS_EARTHING_ID FOREIGN KEY(EARTHING_ID) REFERENCES EARTHING_LPS_DESCRIPTION(EARTHING_ID) ON DELETE CASCADE
							);
							




				CREATE TABLE EARTHELECTRODECHAMBER_TABLE(
							EARTHELECTRODECHAMBER_ID INT AUTO_INCREMENT,
							EARTHING_ID INT,
							LOCATION_NUMBER INT,
                            LOCATION_NAME VARCHAR(225),
                            FLAG BOOLEAN,
							PHYSICAL_INSPECTIONOB VARCHAR(225),
							PHYSICAL_INSPECTIONREM VARCHAR(225),
							CHAMBER_TYPEOB VARCHAR(225),
							CHAMBER_TYPEREM VARCHAR(225),
							CHAMBER_SIZEOB VARCHAR(225),
							CHAMBER_SIZEREM VARCHAR(225),
							MAXIMUMWITHSTAND_LOADOB VARCHAR(225),
							MAXIMUMWITHSTAND_LOADREM VARCHAR(225),
							CHAMBER_PLACED_SOILOB VARCHAR(225),
							CHAMBER_PLACED_SOILREM VARCHAR(225),
							TOTAL_CHAMBERSNOOB VARCHAR(225),
							TOTAL_CHAMBERSNOREM VARCHAR(225),
							INSPECTED_CHAMBERINOB VARCHAR(225),
							INSPECTED_CHAMBERINREM VARCHAR(225),
							INSPECTED_PASSEDINOB VARCHAR(225),
							INSPECTED_PASSEDINREM VARCHAR(225),
							INSPECTED_FAILEDINOB VARCHAR(225),
							INSPECTED_FAILEDINREM VARCHAR(225),
							
							
							
							CONSTRAINT PK_EARTHELECTRODECHAMBER_ID PRIMARY KEY(EARTHELECTRODECHAMBER_ID),
							CONSTRAINT FK_EARTHELECTRODECHAMBER_EARTHING_ID FOREIGN KEY(EARTHING_ID) REFERENCES EARTHING_LPS_DESCRIPTION(EARTHING_ID) ON DELETE CASCADE
							);



				CREATE TABLE EARTHING_SYSTEM_TABLE(
							EARTHING_SYSTEM_ID INT AUTO_INCREMENT,
							EARTHING_ID INT,
							BURIED_ELECTRODEOB VARCHAR(225),
							BURIED_ELECTRODEREM VARCHAR(225),
							DEPTH_OF_ELECTRODEOB VARCHAR(225),
							DEPTH_OF_ELECTRODEREM VARCHAR(225),
							EAST_OB VARCHAR(225),
							EAST_REM VARCHAR(225),
							WEST_OB VARCHAR(225),
							WEST_REM VARCHAR(225),
							NORTH_OB VARCHAR(225),
							NORTH_REM VARCHAR(225),
							SOUTH_OB VARCHAR(225),
							SOUTH_REM VARCHAR(225),
							RINGEARTHWALL_DISTANCE_OB VARCHAR(225),
							RINGEARTHWALL_DISTANCE_REM VARCHAR(225),
							RINGEARTHWALL_EAST_OB VARCHAR(225),
							RINGEARTHWALL_EAST_REM VARCHAR(225),
							RINGEARTHWALL_WEST_OB VARCHAR(225),
							RINGEARTHWALL_WEST_REM VARCHAR(225),
							RINGEARTHWALL_NORTH_OB VARCHAR(225),
							RINGEARTHWALL_NORTH_REM VARCHAR(225),
							RINGEARTHWALL_SOUTH_OB VARCHAR(225),
							RINGEARTHWALL_SOUTH_REM VARCHAR(225),
							JOINTSMADE_BRAZING_OB VARCHAR(225),
							JOINTSMADE_BRAZING_REM VARCHAR(225),
							MATERIAL_OF_EARTHELECTRODE_OB VARCHAR(225),
							MATERIAL_OF_EARTHELECTRODE_REM VARCHAR(225),
							SIZE_OFEARTHELECTRODE_OB VARCHAR(225),
							SIZE_OFEARTHELECTRODE_REM VARCHAR(225),
							MAXIMUMDISTANCE_EARTHELECTRODEWAL_OB VARCHAR(225),
							MAXIMUMDISTANCE_EARTHELECTRODEWALL_REM VARCHAR(225),
							MINIMUMDISTANCE_EARTHELECTRODEWALL_OB VARCHAR(225),
							MINIMUMDISTANCE_EARTHELECTRODEWALL_REM VARCHAR(225),
							CONSTRAINT PK_EARTHING_SYSTEM_ID PRIMARY KEY(EARTHING_SYSTEM_ID),
							CONSTRAINT FK_EARTHING_SYSTEM_EARTHING_ID FOREIGN KEY(EARTHING_ID) REFERENCES EARTHING_LPS_DESCRIPTION(EARTHING_ID) ON DELETE CASCADE
							);
							
							
				 ------>SPD <--------
 
          CREATE TABLE SPD_TABLE(
				            SPD_ID INT AUTO_INCREMENT,
				            BASIC_LPS_ID INT,
				            USER_NAME VARCHAR(225),
				            MAINS_INCOMING_OB VARCHAR(225),
				            MAINS_INCOMING_REM VARCHAR(225),
				            TOTALMAINS_INCOMING_OB VARCHAR(225),
				            TOTALMAINS_INCOMING_REM VARCHAR(225),
				            NO_PANNELSUPPLITTING_OB VARCHAR(225),
				            NO_PANNELSUPPLITTING_REM VARCHAR(225),
				            TOTAL_NO_OUTDOOREQUIPMENT_OB VARCHAR(225),
				            TOTAL_NO_OUTDOOREQUIPMENT_REM VARCHAR(225),
				            CREATED_BY VARCHAR(255),
						    CREATED_DATE datetime,
						    UPDATED_BY VARCHAR(255),
						    UPDATED_DATE datetime,
				           CONSTRAINT PK_SPD_ID  PRIMARY KEY(SPD_ID)
				            );

           
           CREATE TABLE SPD_DESCRIPTION_TABLE(
			               SPDDESCRIPTION_ID INT AUTO_INCREMENT,
			               SPD_ID INT,
			               SPDDESCRIPTION_ROLE VARCHAR(225),
			               SPD_TYPE_OB VARCHAR(225),
			               SPD_TYPE_RE VARCHAR(225),
			               SPD_APPLICATION_OB VARCHAR(225),
			               SPD_APPLICATION_REM VARCHAR(225),
			               PANEL_NAME_OB VARCHAR(225),
			               PANEL_NAME_REM VARCHAR(225),
			               INCOMING_RATING_OB VARCHAR(225),
			               INCOMING_RATING_REM VARCHAR(225),
			               BACKUPFUSE_CHECK_OB VARCHAR(225),
			               BACKUPFUSE_CHECK_REM VARCHAR(225),
			               CONNECTING_WIRELENGTH_OB VARCHAR(225),
			               CONNECTING_WIRELENGTH_REM VARCHAR(225),
			               CONNECTING_WIRESIZE_OB VARCHAR(225),
			               CONNECTING_WIRESIZE_REM VARCHAR(225),
			               CONSTRAINT PK_SPDDESCRIPTION_ID  PRIMARY KEY(SPDDESCRIPTION_ID),
			               CONSTRAINT FK_SPD_ID FOREIGN KEY(SPD_ID) REFERENCES SPD_TABLE(SPD_ID) ON DELETE CASCADE
			        );

							
		 -----------> LPS  SEPARATE-DISTANCE-TABLE <----------	
							
			CREATE TABLE SEPERATION_DISTANCE_TABLE(
		                SEPERATION_DISTANCE_ID INT AUTO_INCREMENT,
		                BASIC_LPS_ID  VARCHAR(225),
		                USER_NAME  VARCHAR(225),
		                CREATED_BY VARCHAR(255),
			            CREATED_DATE datetime,
			            UPDATED_BY VARCHAR(255),
			            UPDATED_DATE datetime,
		                CONSTRAINT PK_SEPERATION_DISTANCE_ID  PRIMARY KEY(SEPERATION_DISTANCE_ID)
		
		);


            CREATE TABLE SEPERATION_DISTANCE_DESCRIPTION_TABLE(
	                    SEPERATION_DISTANCE_DESC_ID INT AUTO_INCREMENT,
	                    SEPERATION_DISTANCE_ID  INT,
	                    FLAG BOOLEAN,
	                    SEPERATION_DISTANCE_DESC VARCHAR(225),
	                    SEPERATION_DISTANCE_OB VARCHAR(225),
	                    SEPERATION_DISTANCE_REM VARCHAR(225),
	                    CONSTRAINT PK_SEPERATION_DISTANCE_DESC_ID  PRIMARY KEY(SEPERATION_DISTANCE_DESC_ID),
	                    CONSTRAINT FK_SEPERATION_DISTANCE_ID FOREIGN KEY(SEPERATION_DISTANCE_ID) REFERENCES SEPERATION_DISTANCE_TABLE(SEPERATION_DISTANCE_ID) ON DELETE CASCADE
         );
						
         
         --------->LPS  EARTHSTUD<--------
 
        CREATE TABLE EARTH_STUD_DESCRIPTION(
			            EARTH_STUD_DESC_ID INT AUTO_INCREMENT,
			            BASIC_LPS_ID INT,
			            USER_NAME VARCHAR(225),
			            EARTH_STUDVISIBILITYOB VARCHAR(225),
			            EARTH_STUDVISIBILITYREM VARCHAR(225),
			            EARTH_STUDBENDOB VARCHAR(225),
			            EARTH_STUDBENDREM VARCHAR(225),
			            PROPER_BONDINGRAILOB VARCHAR(225),
			            PROPER_BONDINGRAILREM VARCHAR(225),
			            PHYSICAL_DAMAGESTUDOB VARCHAR(225),
			            PHYSICA_LDAMAGESTUDREM VARCHAR(225),
			            CONTINUTY_EXISTAEARTHOB VARCHAR(225),
			            CONTINUTY_EXISTAEARTHREM VARCHAR(225),
			            CREATED_BY VARCHAR(255),
						CREATED_DATE datetime,
					    UPDATED_BY VARCHAR(255),
					    UPDATED_DATE datetime,
			           CONSTRAINT PK_EARTH_STUD_DESC_ID PRIMARY KEY(EARTH_STUD_DESC_ID)
           );